repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: requirements-txt-fixer
      name: Requirements
      types: [file]
      exclude_types: ['image']
    - id: debug-statements
      name: Debugging
      language: python
      types: [file, python]
      exclude_types: ['image']
    - id: trailing-whitespace
      name: Trailing Whitespace
      language: python
      types: [file]
      exclude_types: ['image', 'binary', 'executable']
    - id: end-of-file-fixer
      name: EOF Newlines
      language: python
      types: [file]
      exclude_types: ['image', 'binary', 'executable']
    - id: check-yaml
      name: YAML Structure
      language: python
      args: ['--unsafe']
    - id: check-toml
      name: TOML Structure
    - id: check-merge-conflict
      name: Merge Conflicts
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.3.2'
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        name: Black Formatting
        language: python
        types: [ file, python ]
#  - repo: https://github.com/pycqa/isort
#    rev: 5.11.4
#    hooks:
#      - id: isort
#        name: isort Formatting
#        language: python
#        types: [file, python]
ci:
  autoupdate_branch: "unstable"
  autofix_prs: true
  autoupdate_commit_msg: "ci: weekly check."
  autoupdate_schedule: weekly
  autofix_commit_msg: "ci: correct from checks."
